import type { PlanValues } from "./planTemplates";

/**
 * Standard-field values extracted from the official 2026 SBC documents for the
 * Health plans on the site (AEA/EBPA prefixes ignored; only plans already on the
 * site are included). Applied to matching plans via /api/admin/plans/apply-sbc.
 * Source of truth is the SBC PDFs; verify in the editor before relying on them.
 */
export const PLAN_SEED_VALUES: Record<string, PlanValues> = {
  "Deluxe Platinum": {
    "deductible_individual": "$100",
    "deductible_family": "$200",
    "oop_individual": "$3,000",
    "oop_family": "$6,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$20 copay/visit",
    "specialist": "$30 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$0 copay/prescription (retail and mail order)",
    "rx_preferred": "$30 copay/prescription (retail); $75 copay/prescription (mail order)",
    "rx_nonpreferred": "$60 copay/prescription (retail); $150 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "Facility: $150 copay/visit; Physician: $40 copay/visit",
    "urgent_care": "$40 copay/visit",
    "inpatient": "$150 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $150 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Elite Health": {
    "deductible_individual": "$1,000",
    "deductible_family": "$2,000",
    "oop_individual": "$1,000",
    "oop_family": "$2,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "No charge",
    "specialist": "No charge",
    "preventive": "No charge",
    "rx_generic": "No charge (retail and mail order)",
    "rx_preferred": "$75 copay/prescription (retail) and $150 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail) and $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "$250 copay/visit",
    "urgent_care": "No charge",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Freedom Platinum": {
    "deductible_individual": "$100",
    "deductible_family": "$200",
    "oop_individual": "$3,000",
    "oop_family": "$6,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$20 copay/visit",
    "specialist": "$30 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$10 copay/prescription (retail); $25 copay/prescription (mail order)",
    "rx_preferred": "Not covered",
    "rx_nonpreferred": "Not covered",
    "rx_specialty": "Not covered",
    "emergency_room": "Facility: $150 copay/visit; Physician: $40 copay/visit",
    "urgent_care": "$40 copay/visit",
    "inpatient": "$150 copay/day (days 1-5)",
    "outpatient": "Office: 20% coinsurance after deductible; Ambulatory Surgical Center: $150 copay/visit; Outpatient Hospital: $150 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Premier Health": {
    "deductible_individual": "$3,000",
    "deductible_family": "$6,000",
    "oop_individual": "$3,000",
    "oop_family": "$6,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "No charge",
    "specialist": "No charge",
    "preventive": "No charge",
    "rx_generic": "No charge (retail and mail order)",
    "rx_preferred": "$75 copay/prescription (retail) and $150 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail) and $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "$250 copay/visit",
    "urgent_care": "No charge",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Choice Gold": {
    "deductible_individual": "$500",
    "deductible_family": "$1,000",
    "oop_individual": "$5,000",
    "oop_family": "$10,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$35 copay/visit",
    "specialist": "$50 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$15 copay/prescription (retail); $37.50 copay/prescription (mail order)",
    "rx_preferred": "$40 copay/prescription (retail); $100 copay/prescription (mail order)",
    "rx_nonpreferred": "$60 copay/prescription (retail); $150 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "Facility: $200 copay/visit; Physician: $50 copay/visit",
    "urgent_care": "$50 copay/visit",
    "inpatient": "$200 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $200 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Freedom Gold": {
    "deductible_individual": "$500",
    "deductible_family": "$1,000",
    "oop_individual": "$5,000",
    "oop_family": "$10,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$35 copay/visit",
    "specialist": "$50 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$10 copay/prescription (retail); $25 copay/prescription (mail order)",
    "rx_preferred": "Not covered",
    "rx_nonpreferred": "Not covered",
    "rx_specialty": "Not covered",
    "emergency_room": "Facility: $200 copay/visit; Physician: $50 copay/visit",
    "urgent_care": "$50 copay/visit",
    "inpatient": "$200 copay/day (days 1-5)",
    "outpatient": "Office: 20% coinsurance after deductible; Ambulatory Surgical Center: $200 copay/visit; Outpatient Hospital: $200 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Select Health": {
    "deductible_individual": "$5,000",
    "deductible_family": "$10,000",
    "oop_individual": "$5,000",
    "oop_family": "$10,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "No charge",
    "specialist": "No charge",
    "preventive": "No charge",
    "rx_generic": "No charge (retail and mail order)",
    "rx_preferred": "$75 copay/prescription (retail) and $150 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail) and $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "$250 copay/visit",
    "urgent_care": "No charge",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Basic Gold": {
    "deductible_individual": "$1,000",
    "deductible_family": "$2,000",
    "oop_individual": "$6,000",
    "oop_family": "$12,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$40 copay/visit",
    "specialist": "$60 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$15 copay/prescription (retail) and $37.50 copay/prescription (mail order)",
    "rx_preferred": "$50 copay/prescription (retail) and $125 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail) and $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "Facility: $250 copay/visit; Physician: $60 copay/visit",
    "urgent_care": "$60 copay/visit",
    "inpatient": "$250 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $250 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Preferred Silver": {
    "deductible_individual": "$2,000",
    "deductible_family": "$4,000",
    "oop_individual": "$6,350",
    "oop_family": "$12,700",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$40 copay/visit",
    "specialist": "$60 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$15 copay/prescription (retail); $37.50 copay/prescription (mail order)",
    "rx_preferred": "$60 copay/prescription (retail); $150 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail); $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "Facility: $300 copay/visit; Physician: $60 copay/visit",
    "urgent_care": "$60 copay/visit",
    "inpatient": "$300 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $300 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Enhanced Silver": {
    "deductible_individual": "$3,000",
    "deductible_family": "$6,000",
    "oop_individual": "$7,900",
    "oop_family": "$15,800",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$40 copay/visit",
    "specialist": "$65 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$15 copay/prescription (retail); $37.50 copay/prescription (mail order)",
    "rx_preferred": "$75 copay/prescription (retail); $187.50 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail); $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "Facility: $400 copay/visit; Physician: $65 copay/visit",
    "urgent_care": "$65 copay/visit",
    "inpatient": "$400 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $400 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Freedom Silver": {
    "deductible_individual": "$2,000",
    "deductible_family": "$4,000",
    "oop_individual": "$6,350",
    "oop_family": "$12,700",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$40 copay/visit",
    "specialist": "$60 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$10 copay/prescription (retail); $25 copay/prescription (mail order)",
    "rx_preferred": "Not covered",
    "rx_nonpreferred": "Not covered",
    "rx_specialty": "Not covered",
    "emergency_room": "Facility: $300 copay/visit; Physician: $60 copay/visit",
    "urgent_care": "$60 copay/visit",
    "inpatient": "$300 copay/day (days 1-5)",
    "outpatient": "Office: 20% coinsurance after deductible; Ambulatory Surgical Center: $300 copay/visit; Outpatient Hospital: $300 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Core Health": {
    "deductible_individual": "$9,000",
    "deductible_family": "$18,000",
    "oop_individual": "$9,000",
    "oop_family": "$18,000",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "No charge",
    "specialist": "No charge",
    "preventive": "No charge",
    "rx_generic": "No charge (retail and mail order)",
    "rx_preferred": "$75 copay/prescription (retail) and $150 copay/prescription (mail order)",
    "rx_nonpreferred": "$100 copay/prescription (retail) and $250 copay/prescription (mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "$250 copay/visit",
    "urgent_care": "No charge",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Classic Silver": {
    "deductible_individual": "$4,000",
    "deductible_family": "$8,000",
    "oop_individual": "$8,150",
    "oop_family": "$16,300",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$40 copay/visit",
    "specialist": "$70 copay/visit",
    "preventive": "No charge",
    "rx_nonpreferred": "$100 copay/prescription (retail); $250 copay/prescription (mail order)",
    "emergency_room": "Facility: $450 copay/visit; Physician: $70 copay/visit",
    "urgent_care": "$70 copay/visit",
    "inpatient": "$450 copay/day (days 1-5)",
    "outpatient": "Ambulatory Surgical Center: No charge; Outpatient Hospital: $450 copay/visit",
    "coinsurance": "20% after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Saver HSA": {
    "deductible_individual": "$6,450",
    "deductible_family": "$12,900",
    "oop_individual": "$6,450",
    "oop_family": "$12,900",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "No charge after deductible",
    "specialist": "No charge after deductible",
    "preventive": "No charge",
    "rx_generic": "No charge after deductible (retail and mail order)",
    "rx_preferred": "No charge after deductible (retail and mail order)",
    "rx_nonpreferred": "No charge after deductible (retail and mail order)",
    "rx_specialty": "Specialty drugs are not covered under the medical plan.",
    "emergency_room": "No charge after deductible",
    "urgent_care": "No charge after deductible",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  },
  "Freedom Bronze": {
    "deductible_individual": "$8,550",
    "deductible_family": "$17,100",
    "oop_individual": "$8,550",
    "oop_family": "$17,100",
    "network": "This plan does not use a provider network. You can receive covered services from any provider.",
    "primary_care": "$35 copay/visit",
    "specialist": "$50 copay/visit",
    "preventive": "No charge",
    "rx_generic": "$10 copay/prescription (retail); $25 copay/prescription (mail order)",
    "rx_preferred": "Not covered",
    "rx_nonpreferred": "Not covered",
    "rx_specialty": "Not covered",
    "emergency_room": "No charge after deductible",
    "urgent_care": "No charge after deductible",
    "inpatient": "No charge after deductible",
    "outpatient": "No charge after deductible",
    "telehealth": "No charge (virtual visits)"
  }
};
